name: Unit Tests
on: [push, pull_request]
jobs:
  go_tests:
    name: Go Tests
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - run: go test ./...
